PHẦN 1: KHÁM PHÁ TENSOR

In [1]:
import torch
import numpy as np

# Tạo tensor từ list
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f"Tensor từ list:\n {x_data}\n")

# Tạo tensor từ NumPy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor từ NumPy array:\n {x_np}\n")

# Tạo tensor với các giá trị ngẫu nhiên hoặc hằng số
x_ones = torch.ones_like(x_data) # tạo tensor gồm các số 1 có cùng shape với x_data
print(f"Ones Tensor:\n {x_ones}\n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # tạo tensor ngẫu nhiên
print(f"Random Tensor:\n {x_rand}\n")

# In ra shape, dtype, và device của tensor
print(f"Shape của tensor: {x_rand.shape}")
print(f"Datatype của tensor: {x_rand.dtype}")
print(f"Device lưu trữ tensor: {x_rand.device}")

Tensor từ list:
 tensor([[1, 2],
        [3, 4]])

Tensor từ NumPy array:
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Ones Tensor:
 tensor([[1, 1],
        [1, 1]])

Random Tensor:
 tensor([[0.2649, 0.8935],
        [0.7887, 0.5429]])

Shape của tensor: torch.Size([2, 2])
Datatype của tensor: torch.float32
Device lưu trữ tensor: cpu


TASK 1.2: CÁC PHÉP TOÁN TRÊN TENSOR

In [2]:
print("=== Task 1.2: Các phép toán trên Tensor ===")

# 1. Cộng x_data với chính nó
add_result = x_data + x_data
print(f"Cộng x_data với chính nó:\n{add_result}\n")

# 2. Nhân x_data với 5
mul_result = x_data * 5
print(f"Nhân x_data với 5:\n{mul_result}\n")

# 3. Nhân ma trận x_data với x_data.T
matmul_result = x_data @ x_data.T
print(f"Nhân ma trận x_data @ x_data.T:\n{matmul_result}\n")


=== Task 1.2: Các phép toán trên Tensor ===
Cộng x_data với chính nó:
tensor([[2, 4],
        [6, 8]])

Nhân x_data với 5:
tensor([[ 5, 10],
        [15, 20]])

Nhân ma trận x_data @ x_data.T:
tensor([[ 5, 11],
        [11, 25]])



TASK 1.3 – INDEXING VÀ SLICING

In [3]:
print("=== Task 1.3: Indexing và Slicing ===")

# 1. Lấy hàng đầu tiên
row1 = x_data[0]
print(f"Hàng đầu tiên:\n{row1}\n")

# 2. Lấy cột thứ hai
col2 = x_data[:, 1]
print(f"Cột thứ hai:\n{col2}\n")

# 3. Lấy giá trị hàng 2 cột 2
value_22 = x_data[1, 1]
print(f"Giá trị tại hàng 2, cột 2: {value_22}\n")


=== Task 1.3: Indexing và Slicing ===
Hàng đầu tiên:
tensor([1, 2])

Cột thứ hai:
tensor([2, 4])

Giá trị tại hàng 2, cột 2: 4



TASK 1.4 – THAY ĐỔI HÌNH DẠNG TENSOR

In [4]:
print("=== Task 1.4: Thay đổi hình dạng Tensor ===")

# Tạo tensor random shape (4, 4)
rand_tensor = torch.rand(4, 4)
print(f"Tensor random ban đầu (4,4):\n{rand_tensor}\n")

# Reshape thành (16, 1)
reshaped_tensor = rand_tensor.view(16, 1)  # hoặc rand_tensor.reshape(16, 1)
print(f"Tensor sau khi reshape thành (16,1):\n{reshaped_tensor}")


=== Task 1.4: Thay đổi hình dạng Tensor ===
Tensor random ban đầu (4,4):
tensor([[0.9947, 0.0322, 0.0368, 0.4303],
        [0.2152, 0.5746, 0.5584, 0.3634],
        [0.3612, 0.0082, 0.3496, 0.8010],
        [0.1900, 0.0725, 0.7435, 0.5033]])

Tensor sau khi reshape thành (16,1):
tensor([[0.9947],
        [0.0322],
        [0.0368],
        [0.4303],
        [0.2152],
        [0.5746],
        [0.5584],
        [0.3634],
        [0.3612],
        [0.0082],
        [0.3496],
        [0.8010],
        [0.1900],
        [0.0725],
        [0.7435],
        [0.5033]])


PHẦN 2: TỰ ĐỘNG TÍNH ĐẠO HÀM VỚI `autograd`

In [5]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3

# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x000001E77376FB80>
Đạo hàm của z theo x: tensor([18.])


In [6]:
# QUESTION: Thử gọi z.backward() thêm 1 lần
z.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
# NHẬN XÉT: Mặc định, PyTorch giải phóng computational graph sau khi thực hiện .backward() nhằm tiết kiệm bộ nhớ
# trừ khi có yêu cầu giữ lại, z.backward(retain_graph=True)
# => Nhưng gradient sẽ cộng dồn, không reset

PHẦN 3: XÂY DỰNG MÔ HÌNH ĐẦU TIÊN VỚI `torch.nn`

TASK 3.1: LỚP `nn.linear`

In [7]:
# Lớp nn.Linear thực hiện một phép biến đổi tuyến tính y = xA^T + b.
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều

# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)
print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Original tensor:\n {input_tensor}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Original tensor:
 tensor([[-0.4312, -1.3338,  0.2170, -0.5862, -0.0319],
        [-1.1398,  1.1832, -0.1005, -1.6019, -1.4577],
        [ 0.5651, -0.1061, -0.0878, -0.9836,  0.4954]])
Output:
 tensor([[ 0.4220, -0.3629],
        [-0.3322, -0.0946],
        [ 0.0060, -0.0544]], grad_fn=<AddmmBackward0>)


TASK 3.2: LỚP `nn.embedding`

In [8]:
# Lớp nn.Embedding là một bảng tra cứu, dùng để ánh xạ các chỉ số của từ thành các vector embedding.

# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.7008, -0.1423, -0.5862],
        [ 0.3810,  0.2561,  1.7654],
        [-0.7272,  0.8784,  0.1362],
        [ 2.4089, -0.2594,  0.5800]], grad_fn=<EmbeddingBackward0>)


TASK 3.3: KẾT HỢP THÀNH MỘT `nn.module`

In [9]:
from torch import nn

class MyFirstModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
        super(MyFirstModel, self).__init__()
        
        # Định nghĩa các lớp (layer) bạn sẽ dùng
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.linear = nn.Linear(embedding_dim, hidden_dim)
        self.activation = nn.ReLU()   # Hàm kích hoạt
        self.output_layer = nn.Linear(hidden_dim, output_dim)

    def forward(self, indices):
        # 1. Lấy embedding
        embeds = self.embedding(indices)         # (batch, seq_len, embedding_dim)

        # 2. Truyền qua lớp linear và activation
        hidden = self.activation(self.linear(embeds))  # áp dụng theo từng bước thời gian

        # 3. Truyền qua lớp output
        output = self.output_layer(hidden)

        return output

# Khởi tạo và kiểm tra mô hình
model = MyFirstModel(
    vocab_size=100,
    embedding_dim=16,
    hidden_dim=8,
    output_dim=2
)

input_data = torch.LongTensor([[1, 2, 5, 9]])  # một câu gồm 4 từ (batch size = 1)
output_data = model(input_data)

print("Model output shape:", output_data.shape)
print("Output:\n", output_data)


Model output shape: torch.Size([1, 4, 2])
Output:
 tensor([[[-0.2513,  0.8019],
         [-0.0335,  0.1960],
         [ 0.0429,  0.1761],
         [-0.1017,  0.2990]]], grad_fn=<ViewBackward0>)
